// Action Types

export const POSTS_GETALL = 'POSTS_GETALL';
export const POSTS_GETALL_START = 'POSTS_GETALL_START';
export const POSTS_GETALL_SUCCESS = 'POSTS_GETALL_SUCCESS';
export const POSTS_GETALL_FAIL = 'POSTS_GETALL_FAIL';

export const POSTS_SINGLE = 'POSTS_SINGLE';
export const POSTS_SINGLE_START = 'POSTS_SINGLE_START';
export const POSTS_SINGLE_SUCCESS = 'POSTS_SINGLE_SUCCESS';
export const POSTS_SINGLE_FAIL = 'POSTS_SINGLE_FAIL';

export const POSTS_CREATE = 'POSTS_CREATE';
export const POSTS_CREATE_START = 'POSTS_CREATE_START';
export const POSTS_CREATE_SUCCESS = 'POSTS_CREATE_SUCCESS';
export const POSTS_CREATE_FAIL = 'POSTS_CREATE_FAIL';

export const POSTS_UPDATE = 'POSTS_UPDATE';
export const POSTS_UPDATE_START = 'POSTS_UPDATE_START';
export const POSTS_UPDATE_SUCCESS = 'POSTS_UPDATE_SUCCESS';
export const POSTS_UPDATE_FAIL = 'POSTS_UPDATE_FAIL';

export const POSTS_REMOVE = 'POSTS_REMOVE';
export const POSTS_REMOVE_START = 'POSTS_REMOVE_START';
export const POSTS_REMOVE_SUCCESS = 'POSTS_REMOVE_SUCCESS';
export const POSTS_REMOVE_FAIL = 'POSTS_REMOVE_FAIL';
