// Action Types

export const COMMENTS_GETALL = 'COMMENTS_GETALL';
export const COMMENTS_GETALL_START = 'COMMENTS_GETALL_START';
export const COMMENTS_GETALL_SUCCESS = 'COMMENTS_GETALL_SUCCESS';
export const COMMENTS_GETALL_FAIL = 'COMMENTS_GETALL_FAIL';
